language: python
python:
- '2.7'
before_script:
- cd ..
- wget http://googleappengine.googlecode.com/files/google_appengine_1.8.8.zip
- unzip google_appengine_1.8.8.zip
- rm google_appengine_1.8.8.zip
- sudo apt-get install python-imaging
install:
- sudo pip install -r requirements.txt --use-mirrors
- sudo pip install nose
- sudo pip install WebTest
- sudo pip install nosegae
notifications:
  email:
    on_success: change
    on_failure: always
script:
- git clone https://github.com/yixianlee2011/mastermind_1.git deploy
- cd deploy
- /usr/local/bin/nosetests
after_success:
- cd ..
- google_appengine/appcfg.py --oauth2_refresh_token=$MY_GAE_TOKEN update deploy/
env:
  global:
    secure: g/K6EIhjk9D15Rpf6IhWDDe1kjC1VXu0guyLGlt3tvRjNO3CrYhDw4uTiwhbsUMw/tAuBNHhjU/b/AxaFbbCunHzbN451JNeWwKpB9iAXkJTfgPNyTysNcBkz1f5P0/ZM0SSRPEfUduRGoF1yQBrhwI5zmPjF0sk0V67dxfBf6M=
