language: python
python:
- '2.7'
before_script:
- cd ..
- wget http://googleappengine.googlecode.com/files/google_appengine_1.8.8.zip
- unzip google_appengine_1.8.8.zip
- rm google_appengine_1.8.8.zip
- sudo apt-get install python-imaging
install:
- sudo pip install -r requirements.txt --use-mirrors
- sudo pip install nose
- sudo pip install WebTest
- sudo pip install nosegae
script:
- git clone https://github.com/yixianlee2011/mastermind_1 deploy
- cd deploy
- /usr/local/bin/nosetests
after_success:
- google_appengine/appcfg.py --oauth2_refresh_token=$MY_GAE_TOKEN update deploy/
env:
  global:
    secure: BZASLjvfSXxaeHF2UIN21AQjwaCdjBBfMcY0SE//Q8rChR2/CZ8ssPnQLtqWnn2tRY1yDW3wp/tWZ7cUPPRo+Bm26g8jCKpC3gXhYRFF31msp6uw/nGA8bBzK5P7kOdUI4BNJxG1Czc1rvwcRC9QZ5eXL9zV2s/huGvssR1bWjA=
